-- liquibase formatted sql

-- changeset liquibase:rseni-prepare-schema

create schema ni;

create schema nibatch;

set search_path=ni;

create extension pgcrypto; 

create role niapi with login password 'ChangeMeToARandomGUID';

create role nipub with login password 'ChangeMeToARandomGUID';

grant usage on schema ni to niapi;

grant usage on schema ni to nipub;

grant usage on schema nibatch to nipub;

set search_path=nibatch;

-- COPIED FROM HERE https://raw.githubusercontent.com/spring-projects/spring-batch/main/spring-batch-core/src/main/resources/org/springframework/batch/core/schema-postgresql.sql

CREATE TABLE BATCH_JOB_INSTANCE  (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT ,
	JOB_NAME VARCHAR(100) NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION  (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT  ,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR(10) ,
	EXIT_CODE VARCHAR(2500) ,
	EXIT_MESSAGE VARCHAR(2500) ,
	LAST_UPDATED TIMESTAMP,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
	JOB_EXECUTION_ID BIGINT NOT NULL ,
	PARAMETER_NAME VARCHAR(100) NOT NULL ,
	PARAMETER_TYPE VARCHAR(100) NOT NULL ,
	PARAMETER_VALUE VARCHAR(2500) ,
	IDENTIFYING CHAR(1) NOT NULL ,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION  (
	STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT NOT NULL,
	STEP_NAME VARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR(10) ,
	COMMIT_COUNT BIGINT ,
	READ_COUNT BIGINT ,
	FILTER_COUNT BIGINT ,
	WRITE_COUNT BIGINT ,
	READ_SKIP_COUNT BIGINT ,
	WRITE_SKIP_COUNT BIGINT ,
	PROCESS_SKIP_COUNT BIGINT ,
	ROLLBACK_COUNT BIGINT ,
	EXIT_CODE VARCHAR(2500) ,
	EXIT_MESSAGE VARCHAR(2500) ,
	LAST_UPDATED TIMESTAMP,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT ,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT ,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;

-- COPIED TO HERE from https://raw.githubusercontent.com/spring-projects/spring-batch/main/spring-batch-core/src/main/resources/org/springframework/batch/core/schema-postgresql.sql

GRANT SELECT,INSERT,UPDATE,DELETE ON nibatch.BATCH_JOB_INSTANCE TO nipub;
GRANT SELECT,INSERT,UPDATE,DELETE ON nibatch.BATCH_JOB_EXECUTION TO nipub;
GRANT SELECT,INSERT,UPDATE,DELETE ON nibatch.BATCH_JOB_EXECUTION_PARAMS TO nipub;
GRANT SELECT,INSERT,UPDATE,DELETE ON nibatch.BATCH_STEP_EXECUTION TO nipub;
GRANT SELECT,INSERT,UPDATE,DELETE ON nibatch.BATCH_STEP_EXECUTION_CONTEXT TO nipub;
GRANT SELECT,INSERT,UPDATE,DELETE ON nibatch.BATCH_JOB_EXECUTION_CONTEXT TO nipub;

GRANT USAGE ON nibatch.BATCH_STEP_EXECUTION_SEQ TO nipub;
GRANT USAGE ON nibatch.BATCH_JOB_EXECUTION_SEQ TO nipub;
GRANT USAGE ON nibatch.BATCH_JOB_SEQ TO nipub;


set search_path=ni;

