/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package rs.gov.mduls.einicijative.niapi.interfaces;

import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.core.user.OAuth2User;
import rs.gov.mduls.einicijative.niapi.model.InicijatorInicijativaOdgovor;
import rs.gov.mduls.einicijative.niapi.model.InicijatorInicijativaZahtev;
import rs.gov.mduls.einicijative.niapi.model.InicijatorListaInicijativaOdgovor;
import rs.gov.mduls.einicijative.niapi.model.InicijatorNovaInicijativaOdgovor;
import rs.gov.mduls.einicijative.niapi.model.InicijatorPozivnicaOdgovor;
import rs.gov.mduls.einicijative.niapi.model.InicijatorPozivnicaZahtev;
import rs.gov.mduls.einicijative.niapi.model.InicijatorPrilogInicijativeOdgovor;
import rs.gov.mduls.einicijative.niapi.model.InicijatorPrilogInicijativeZahtev;
import rs.gov.mduls.einicijative.niapi.model.InicijatorProfilBiografijaZahtev;
import rs.gov.mduls.einicijative.niapi.model.InicijatorProfilEmailZahtev;
import rs.gov.mduls.einicijative.niapi.model.InicijatorProfilOdgovor;
import rs.gov.mduls.einicijative.niapi.model.Uspeh;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-09-17T13:23:05.888263500+01:00[Europe/London]")
@Validated
public interface InicijatorApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PUT /inicijator/biografija
     * Inicijator postavlja svoju biografiju
     *
     * @param inicijatorProfilBiografijaZahtev  (required)
     * @return Uspeh (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/inicijator/biografija",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Uspeh> inicijatorBiografijaPut(
            @AuthenticationPrincipal OAuth2User principal,
            @Valid @RequestBody InicijatorProfilBiografijaZahtev inicijatorProfilBiografijaZahtev
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"poruka\" : \"poruka\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /inicijator/email
     * Inicijator podešava svoju email adresu za kontakt
     *
     * @param inicijatorProfilEmailZahtev  (required)
     * @return Uspeh (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/inicijator/email",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Uspeh> inicijatorEmailPut(
            @AuthenticationPrincipal OAuth2User principal,
            @Valid @RequestBody InicijatorProfilEmailZahtev inicijatorProfilEmailZahtev
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"poruka\" : \"poruka\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /inicijator/inicijativa/{idInicijative}
     * Detalji inicijative
     *
     * @param idInicijative  (required)
     * @return Detalji inicijative (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/inicijator/inicijativa/{idInicijative}",
        produces = { "application/json" }
    )
    default ResponseEntity<InicijatorInicijativaOdgovor> inicijatorInicijativaIdInicijativeGet(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idInicijative") Long idInicijative
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"detaljiInicijative\" : { \"idInicijative\" : 0, \"trnOdbijanjaZahteva\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"beleskaSaSednice\" : \"beleskaSaSednice\", \"trnZahteva\" : \"2000-01-23T04:56:07.000+00:00\", \"prilozi\" : [ { \"obrisan\" : true, \"urlPriloga\" : \"urlPriloga\", \"sortiranje\" : 1, \"nazivPriloga\" : \"nazivPriloga\" }, { \"obrisan\" : true, \"urlPriloga\" : \"urlPriloga\", \"sortiranje\" : 1, \"nazivPriloga\" : \"nazivPriloga\" } ], \"tekstInicijative\" : \"tekstInicijative\", \"razlogOdbijanjaZahteva\" : \"razlogOdbijanjaZahteva\", \"inicijator\" : \"inicijator\", \"promene\" : [ { \"trnPromene\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"detaljiPromene\" : \"detaljiPromene\" }, { \"trnPromene\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"detaljiPromene\" : \"detaljiPromene\" } ], \"nivoVlasti\" : \"nivoVlasti\", \"trnPodnosenja\" : \"2000-01-23T04:56:07.000+00:00\", \"tipInicijative\" : \"tipInicijative\", \"datumPokretanja\" : \"2000-01-23\", \"emailZaKontakt\" : \"emailZaKontakt\", \"datumOdluke\" : \"2000-01-23\", \"nazivInicijative\" : \"nazivInicijative\", \"jedinicaVlasti\" : \"jedinicaVlasti\", \"prihvacena\" : true, \"clanoviInicijativnogOdbora\" : [ { \"trnOdustajanjaOdClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"aktivan\" : true, \"imePrezime\" : \"imePrezime\", \"emailZaKontakt\" : \"emailZaKontakt\", \"biografija\" : \"biografija\", \"trnPrihvatanjaClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"godinaRodjenja\" : 6, \"pol\" : \"pol\" }, { \"trnOdustajanjaOdClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"aktivan\" : true, \"imePrezime\" : \"imePrezime\", \"emailZaKontakt\" : \"emailZaKontakt\", \"biografija\" : \"biografija\", \"trnPrihvatanjaClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"godinaRodjenja\" : 6, \"pol\" : \"pol\" } ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /inicijator/inicijativa/{idInicijative}/napusti
     * Član inicijativnog odbora obeležava inicijativu kao napuštenu (pre podnošenja)
     *
     * @param idInicijative  (required)
     * @return Uspeh (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/inicijator/inicijativa/{idInicijative}/napusti",
        produces = { "application/json" }
    )
    default ResponseEntity<Uspeh> inicijatorInicijativaIdInicijativeNapustiPut(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idInicijative") Long idInicijative
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"poruka\" : \"poruka\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /inicijator/inicijativa/{idInicijative}/podnesi
     * Član inicijativnog odbora podnosi inicijativu na formalnu proveru predsedniku skupštine
     *
     * @param idInicijative  (required)
     * @return Uspeh (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/inicijator/inicijativa/{idInicijative}/podnesi",
        produces = { "application/json" }
    )
    default ResponseEntity<Uspeh> inicijatorInicijativaIdInicijativePodnesiPut(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idInicijative") Long idInicijative
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"poruka\" : \"poruka\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /inicijator/inicijativa/{idInicijative}/pokreni
     * Član inicijativnog odbora pokreće inicijativu koja je skupila dovoljan broj potpisa
     *
     * @param idInicijative  (required)
     * @return Uspeh (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/inicijator/inicijativa/{idInicijative}/pokreni",
        produces = { "application/json" }
    )
    default ResponseEntity<Uspeh> inicijatorInicijativaIdInicijativePokreniPut(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idInicijative") Long idInicijative
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"poruka\" : \"poruka\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /inicijator/inicijativa/{idInicijative}/pozivnica
     * Inicijator briše pozivnicu
     *
     * @param idInicijative  (required)
     * @return Uspešno kreiran prilog inicijative (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/inicijator/inicijativa/{idInicijative}/pozivnica",
        produces = { "application/json" }
    )
    default ResponseEntity<Uspeh> inicijatorInicijativaIdInicijativePozivnicaDelete(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idInicijative") Long idInicijative
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"poruka\" : \"poruka\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /inicijator/inicijativa/{idInicijative}/pozivnica
     * Inicijator kreira novu pozivnicu budućem članu inicijativnog odboara
     *
     * @param idInicijative  (required)
     * @return Uspešno kreirana pozivnica (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/inicijator/inicijativa/{idInicijative}/pozivnica",
        produces = { "application/json" }
    )
    default ResponseEntity<InicijatorPozivnicaOdgovor> inicijatorInicijativaIdInicijativePozivnicaPost(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idInicijative") Long idInicijative
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"url\" : \"url\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /inicijator/inicijativa/{idInicijative}/pozivnica
     * Pozvani građanin upotrebljava pozivnicu i postaje član inicijativnog odbora
     *
     * @param idInicijative  (required)
     * @param inicijatorPozivnicaZahtev  (required)
     * @return Uspešno kreiran prilog inicijative (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/inicijator/inicijativa/{idInicijative}/pozivnica",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Uspeh> inicijatorInicijativaIdInicijativePozivnicaPut(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idInicijative") Long idInicijative,
            @Valid @RequestBody InicijatorPozivnicaZahtev inicijatorPozivnicaZahtev
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"poruka\" : \"poruka\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /inicijator/inicijativa/{idInicijative}/prilog/{idPriloga}
     * Inicijator briše postojeći prilog inicijative
     *
     * @param idInicijative  (required)
     * @param idPriloga  (required)
     * @return Uspešno kreiran prilog inicijative (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/inicijator/inicijativa/{idInicijative}/prilog/{idPriloga}",
        produces = { "application/json" }
    )
    default ResponseEntity<Uspeh> inicijatorInicijativaIdInicijativePrilogIdPrilogaDelete(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idInicijative") Long idInicijative,
            @PathVariable("idPriloga") Long idPriloga
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"poruka\" : \"poruka\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /inicijator/inicijativa/{idInicijative}/prilog/{idPriloga}
     * Inicijator menja postojeći prilog inicijative
     *
     * @param idInicijative  (required)
     * @param idPriloga  (required)
     * @param inicijatorPrilogInicijativeZahtev  (required)
     * @return Uspešno kreiran prilog inicijative (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/inicijator/inicijativa/{idInicijative}/prilog/{idPriloga}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<InicijatorPrilogInicijativeOdgovor> inicijatorInicijativaIdInicijativePrilogIdPrilogaPut(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idInicijative") Long idInicijative,
            @PathVariable("idPriloga") Long idPriloga,
            @Valid @RequestBody InicijatorPrilogInicijativeZahtev inicijatorPrilogInicijativeZahtev
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"detaljiInicijative\" : { \"idInicijative\" : 0, \"trnOdbijanjaZahteva\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"beleskaSaSednice\" : \"beleskaSaSednice\", \"trnZahteva\" : \"2000-01-23T04:56:07.000+00:00\", \"prilozi\" : [ { \"obrisan\" : true, \"urlPriloga\" : \"urlPriloga\", \"sortiranje\" : 1, \"nazivPriloga\" : \"nazivPriloga\" }, { \"obrisan\" : true, \"urlPriloga\" : \"urlPriloga\", \"sortiranje\" : 1, \"nazivPriloga\" : \"nazivPriloga\" } ], \"tekstInicijative\" : \"tekstInicijative\", \"razlogOdbijanjaZahteva\" : \"razlogOdbijanjaZahteva\", \"inicijator\" : \"inicijator\", \"promene\" : [ { \"trnPromene\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"detaljiPromene\" : \"detaljiPromene\" }, { \"trnPromene\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"detaljiPromene\" : \"detaljiPromene\" } ], \"nivoVlasti\" : \"nivoVlasti\", \"trnPodnosenja\" : \"2000-01-23T04:56:07.000+00:00\", \"tipInicijative\" : \"tipInicijative\", \"datumPokretanja\" : \"2000-01-23\", \"emailZaKontakt\" : \"emailZaKontakt\", \"datumOdluke\" : \"2000-01-23\", \"nazivInicijative\" : \"nazivInicijative\", \"jedinicaVlasti\" : \"jedinicaVlasti\", \"prihvacena\" : true, \"clanoviInicijativnogOdbora\" : [ { \"trnOdustajanjaOdClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"aktivan\" : true, \"imePrezime\" : \"imePrezime\", \"emailZaKontakt\" : \"emailZaKontakt\", \"biografija\" : \"biografija\", \"trnPrihvatanjaClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"godinaRodjenja\" : 6, \"pol\" : \"pol\" }, { \"trnOdustajanjaOdClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"aktivan\" : true, \"imePrezime\" : \"imePrezime\", \"emailZaKontakt\" : \"emailZaKontakt\", \"biografija\" : \"biografija\", \"trnPrihvatanjaClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"godinaRodjenja\" : 6, \"pol\" : \"pol\" } ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /inicijator/inicijativa/{idInicijative}/prilog
     * Inicijator kreira novi prilog inicijative
     *
     * @param idInicijative  (required)
     * @param inicijatorPrilogInicijativeZahtev  (required)
     * @return Uspešno kreiran prilog inicijative (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/inicijator/inicijativa/{idInicijative}/prilog",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<InicijatorPrilogInicijativeOdgovor> inicijatorInicijativaIdInicijativePrilogPost(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idInicijative") Long idInicijative,
            @Valid @RequestBody InicijatorPrilogInicijativeZahtev inicijatorPrilogInicijativeZahtev
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"detaljiInicijative\" : { \"idInicijative\" : 0, \"trnOdbijanjaZahteva\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"beleskaSaSednice\" : \"beleskaSaSednice\", \"trnZahteva\" : \"2000-01-23T04:56:07.000+00:00\", \"prilozi\" : [ { \"obrisan\" : true, \"urlPriloga\" : \"urlPriloga\", \"sortiranje\" : 1, \"nazivPriloga\" : \"nazivPriloga\" }, { \"obrisan\" : true, \"urlPriloga\" : \"urlPriloga\", \"sortiranje\" : 1, \"nazivPriloga\" : \"nazivPriloga\" } ], \"tekstInicijative\" : \"tekstInicijative\", \"razlogOdbijanjaZahteva\" : \"razlogOdbijanjaZahteva\", \"inicijator\" : \"inicijator\", \"promene\" : [ { \"trnPromene\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"detaljiPromene\" : \"detaljiPromene\" }, { \"trnPromene\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"detaljiPromene\" : \"detaljiPromene\" } ], \"nivoVlasti\" : \"nivoVlasti\", \"trnPodnosenja\" : \"2000-01-23T04:56:07.000+00:00\", \"tipInicijative\" : \"tipInicijative\", \"datumPokretanja\" : \"2000-01-23\", \"emailZaKontakt\" : \"emailZaKontakt\", \"datumOdluke\" : \"2000-01-23\", \"nazivInicijative\" : \"nazivInicijative\", \"jedinicaVlasti\" : \"jedinicaVlasti\", \"prihvacena\" : true, \"clanoviInicijativnogOdbora\" : [ { \"trnOdustajanjaOdClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"aktivan\" : true, \"imePrezime\" : \"imePrezime\", \"emailZaKontakt\" : \"emailZaKontakt\", \"biografija\" : \"biografija\", \"trnPrihvatanjaClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"godinaRodjenja\" : 6, \"pol\" : \"pol\" }, { \"trnOdustajanjaOdClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"aktivan\" : true, \"imePrezime\" : \"imePrezime\", \"emailZaKontakt\" : \"emailZaKontakt\", \"biografija\" : \"biografija\", \"trnPrihvatanjaClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"godinaRodjenja\" : 6, \"pol\" : \"pol\" } ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /inicijator/inicijativa/{idInicijative}
     * Inicijator menja postojeću inicijativu (glavni deo)
     *
     * @param idInicijative  (required)
     * @param inicijatorInicijativaZahtev  (required)
     * @return Uspešno promenjena inicijativa (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/inicijator/inicijativa/{idInicijative}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Uspeh> inicijatorInicijativaIdInicijativePut(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idInicijative") Long idInicijative,
            @Valid @RequestBody InicijatorInicijativaZahtev inicijatorInicijativaZahtev
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"poruka\" : \"poruka\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /inicijator/inicijativa/pofaziobrade/{idFazeObrade}
     * Lista inicijativa koje čekaju odobrenje na odgovarajućem nivou
     *
     * @param idFazeObrade  (required)
     * @return Lista inicijativa u čijim je inicijativnim odborima inicijator za zadatu fazu obrade (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/inicijator/inicijativa/pofaziobrade/{idFazeObrade}",
        produces = { "application/json" }
    )
    default ResponseEntity<InicijatorListaInicijativaOdgovor> inicijatorInicijativaPofaziobradeIdFazeObradeGet(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable("idFazeObrade") String idFazeObrade
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"inicijativeZaFazuObrade\" : [ { \"idInicijative\" : 0, \"brPotpisa\" : 1, \"trnPodnosenja\" : \"2000-01-23T04:56:07.000+00:00\", \"tipInicijative\" : \"tipInicijative\", \"datumPokretanja\" : \"2000-01-23\", \"trnZahteva\" : \"2000-01-23T04:56:07.000+00:00\", \"brInicijatora\" : 6, \"nazivInicijative\" : \"nazivInicijative\" }, { \"idInicijative\" : 0, \"brPotpisa\" : 1, \"trnPodnosenja\" : \"2000-01-23T04:56:07.000+00:00\", \"tipInicijative\" : \"tipInicijative\", \"datumPokretanja\" : \"2000-01-23\", \"trnZahteva\" : \"2000-01-23T04:56:07.000+00:00\", \"brInicijatora\" : 6, \"nazivInicijative\" : \"nazivInicijative\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /inicijator/inicijativa
     * Inicijator kreira novu inicijativu
     *
     * @param inicijatorInicijativaZahtev  (required)
     * @return Uspešno kreirana inicijativa (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/inicijator/inicijativa",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<InicijatorNovaInicijativaOdgovor> inicijatorInicijativaPost(
            @AuthenticationPrincipal OAuth2User principal,
            @Valid @RequestBody InicijatorInicijativaZahtev inicijatorInicijativaZahtev
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"detaljiInicijative\" : { \"idInicijative\" : 0, \"trnOdbijanjaZahteva\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"beleskaSaSednice\" : \"beleskaSaSednice\", \"trnZahteva\" : \"2000-01-23T04:56:07.000+00:00\", \"prilozi\" : [ { \"obrisan\" : true, \"urlPriloga\" : \"urlPriloga\", \"sortiranje\" : 1, \"nazivPriloga\" : \"nazivPriloga\" }, { \"obrisan\" : true, \"urlPriloga\" : \"urlPriloga\", \"sortiranje\" : 1, \"nazivPriloga\" : \"nazivPriloga\" } ], \"tekstInicijative\" : \"tekstInicijative\", \"razlogOdbijanjaZahteva\" : \"razlogOdbijanjaZahteva\", \"inicijator\" : \"inicijator\", \"promene\" : [ { \"trnPromene\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"detaljiPromene\" : \"detaljiPromene\" }, { \"trnPromene\" : \"2000-01-23T04:56:07.000+00:00\", \"fazaObrade\" : \"fazaObrade\", \"detaljiPromene\" : \"detaljiPromene\" } ], \"nivoVlasti\" : \"nivoVlasti\", \"trnPodnosenja\" : \"2000-01-23T04:56:07.000+00:00\", \"tipInicijative\" : \"tipInicijative\", \"datumPokretanja\" : \"2000-01-23\", \"emailZaKontakt\" : \"emailZaKontakt\", \"datumOdluke\" : \"2000-01-23\", \"nazivInicijative\" : \"nazivInicijative\", \"jedinicaVlasti\" : \"jedinicaVlasti\", \"prihvacena\" : true, \"clanoviInicijativnogOdbora\" : [ { \"trnOdustajanjaOdClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"aktivan\" : true, \"imePrezime\" : \"imePrezime\", \"emailZaKontakt\" : \"emailZaKontakt\", \"biografija\" : \"biografija\", \"trnPrihvatanjaClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"godinaRodjenja\" : 6, \"pol\" : \"pol\" }, { \"trnOdustajanjaOdClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"aktivan\" : true, \"imePrezime\" : \"imePrezime\", \"emailZaKontakt\" : \"emailZaKontakt\", \"biografija\" : \"biografija\", \"trnPrihvatanjaClanstva\" : \"2000-01-23T04:56:07.000+00:00\", \"godinaRodjenja\" : 6, \"pol\" : \"pol\" } ] } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /inicijator/profil
     * Upit detalja profila inicijatora
     *
     * @return Detalji profila inicijatora (status code 200)
     *         or Aplikativne greske (pogresan sadrzaj) (status code 400)
     *         or Neispravna ili istekla sesija (status code 401)
     *         or Neocekivane programske greske (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/inicijator/profil",
        produces = { "application/json" }
    )
    default ResponseEntity<InicijatorProfilOdgovor> inicijatorProfilGet(
            @AuthenticationPrincipal OAuth2User principal
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"nazivOpstine\" : \"nazivOpstine\", \"imePrezime\" : \"imePrezime\", \"biografija\" : \"biografija\", \"idPola\" : \"М\", \"godinaRodjenja\" : 0, \"emailAdresa\" : \"emailAdresa\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
